CREATE LOGIN [N_Aragorn]
   WITH PASSWORD = N'remotes@2021', DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;
GO
CREATE LOGIN [N_Nagasino]
   WITH PASSWORD = N'remotes@2021', DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;
